---
title: "Presentations"
---

 - Angus, R., Barlow, M.A., & Schulze, W.S. “Failed Exploration Experiments: Helpful, Mostly Harmless, or Harmful?""
    - Presented at the 2018 Organization Science Winter Conference, Park City, UT
    
<br>

 - Barlow, M.A., Angus, R., & Verhaal, J.C. “Standing Out From the Crowd: Optimal Distinctiveness, Market Positioning, and New Market Entry.”
    - Presented at the 2018 Western Academy of Management Annual Meeting, Salt Lake City, UT.
    - Presented at the 2017 SMS Annual Meeting, Houston, TX.
    
<br>

 - Barlow, M.A. & Angus, R. “Portfolio Human Capital: The Interdependence of Entrepreneurial Human Capital Investments.”
    - Presented at the 2017 Western Academy of Management Annual Meeting, Palm Springs, CA.
    
<br>

 - Barlow, M.A. & Angus, R. “Entrepreneurial Action Under Risk and Uncertainty”
    - Presented at the 2016 SMS Annual Meeting, Berlin, Germany

<br>

 - Angus, R. & Barlow, M.A. “Human Capital and Entrepreneurial Performance Under Different Informational Contexts”
    - Presented at the 2016 Academy of Management Annual Conference, Anaheim, CA

<br>

 - Angus, R. & Barlow, M.A., Chen, M. “Learning to Create Value.
    - Presented at the 2015 SMS Annual Meeting, Denver, CO
    - Presented at the 2016 SMS Special Conference on Innovation, Entrepreneurship and Coopetition, Rome, Italy
    - Presented at the 2016 Academy of Management Annual Conference, Anaheim, CA : *Selected for inclusion in 2016 AOM Best Paper Proceedings*

<br>

 - Barlow, M.A. “Do Employee Exits Hurt Organizational Performance? A Contingent View of Human Capital Loss.”
    - Presented at the 2015 Academy of Management Annual Meeting, Vancouver, BC

<br>

 - Barlow, M. A. & Hesterly, W. S. “Catching a Falling Star: Star Human Capital Mobility and the Performance of NFL Teams”
    - Presented at the 2014 SMS Special Conference on Microfoundations, Copenhagen, Denmark
    - Presented at the 2016 Academy of Management Annual Meeting, Anaheim, CA

<br>

 - Barlow, M. A. & Verhaal, J. C. “Guilty by Association: Reputation, Categorical Penalties, and Audience Appeal in the U.S. Craft Brewing Industry”
    - Presented at the 2013 Organizational Ecology Annual Meeting, Budapest Hungary
    - Presented at the 2013 Academy of Management Annual Meeting, Orlando, FL
