---
title: "Research"
---
<br>

## **Research Interests**

My research interests are at the intersection of entrepreneurship, organization theory, and strategic management.  I use various theoretical lenses from across disciplines, with the main focus of my research being the role that different stakeholder groups, both inside and outside of the firm, have on organizational performance and value creation.  With this overarching question, I have three separate, but related research streams.  The first research stream focuses on the creation of entrepreneurial opportunities and entrepreneurial performance.  The second major research stream focuses on the impact that outside stakeholders’ perceptions have on the performance of entrepreneurial organizations. Finally, the third stream focuses on human capital, both in exisintg and nascent organizations.


___


## **Publications**

1. Barlow, M. A., Verhaal, J. C., & Hoskins, J. D. (2016). "Guilty by association: Product-level category stigma and audience expectations in the US craft beer industry." ***Journal of Management***, https://doi.org/10.1177/0149206316657593 
2. Posthuma, R. A., Flores, G. L., Barlow, M. A., & Dworkin, J. B. (2018). "Social signaling and interorganizational relationships: Lessons learned from the professional sports industry." ***Business Horizons***. https://doi.org/10.1016/j.bushor.2018.03.001 

___


## **Manuscripts Under Review**

 1. Barlow, M. A., Verhaal, J. C., & Angus, R. "Getting lost in thecrowd: Optimal distinctiveness, strategic categorization, and newentry on the Google Play app platfor market"
     - Revise & Resubmit (2nd Round) at *Strategic Management Journal*



___


## **Working Papers**
 
 1. Barlow, M.A., Hesterly, W.S., & Verhaal, J.C. "Catching a Falling Star: Mobility of Declining Star Performers, Peer Effects, and Organizational Performance in the National Football League"
     - Target Journal: *Organization Science*
 2. Angus, R. & Barlow, M.A. "Opportunity Value Uncertainty, Role Uncertainty, and the Value of Adaptive Human Capital"
     - Target Journal: *Academy of Management Review (Special Issue on Uncertainty)*
 3. Angus, R., Barlow, M.A., & Schulze, W.S. "Failed Exploration Experiments: Helpful, Mostly Harmless, or Harmful"
     - Target Journal: *Organization Science*
 4. Barlow, M.A. & Angus, R. "Complementary Human Capital Investments and Entrepreneurial Performance"
     - Target Journal: *Strategic Entrepreneurship Journal*
 

___

## **Dissertation**

 - Title: “Micro-foundations of Firm Performance: Three Essays Examining How Human Capital Affects Firm Performance across Strategy and Entrepreneurship”
 - Committee:  Jay Barney (Chair), Bill Hesterly, Sharon Alvarez, Bill Schulze, and Lyda Bigelow

