---
title: ""
---
<br>

# **Teaching Philopsophy**
As a teacher, I strive to foster strategic and critical thinking and aid my students in not only gaining new skills that will help them in their chosen careers, but also on improving basic core skills, including:  analysis, writing, communication, and teamwork.  My overarching goal is to make learning meaningful by moving beyond the textbook and incorporating current, real-world business news with classic studies within the discipline.  My desire is for my students to be well prepared to make immediate contributions to their organizations when they graduate. 
 
Throughout, my pedagogical approach is to incorporate engaged learning strategies including case studies, writing assignments, and collaborative group work.  The case studies highlight different aspects of the frameworks learned during the lectures, and focus on helping the students understand how to make strategic decisions.  The group work includes role-playing and semester-long projects, so that students can see multiple sides of complex issues.  

To achieve my goals in the classroom, I use several different types of projects and assignments.  For example, in my entrepreneurship course, student groups develop venture concepts, and I am use the scientific method to teach them how to test their ideas with the market.  This allows them to refine their original ideas and/or pivot to better ideas that can lead to viable business models that they will present to the class at the end of the semester.  In both my strategy and introductory management courses, I employ a series of writing assignments designed to compel students to think about what they see in the current business world and apply their understanding of course concepts to real events.  For example, I have my students read the Wall Street Journal (or other top business newspapers or publications) and write a short analysis about the strategic decisions discussed or inherent to the news topic.  I want them to think about the situation, what the firm chose to do, and what, if anything, they would do differently. This assignment helps students to gain a better understanding of why businesses do the things they do.  In addition, I hope that my students can improve their writing ability – a key ingredient for business success.  

___

# **Courses Taught**

## ***University of Texas at El Paso***

 - MGMT 3306, Entrepreneurship
    - Most recent syllabus is [here](files/MGMT_3306_Spring_2018_Syllabus.pdf). 
 - MGMT 6352, International Entrepreneurship Ph.D. Seminar
    - Most recent syllabus is [here](files/MGMT_6352_Spring_2018_Syllabus.pdf).
 - MGMT 3303, Introduction to Management & Organizational Behavior
    - Most recent syllabus is [here](files/MGMT_3303_Spring_2017_Syllabus.pdf).
 
## ***University of Utah***

 - STRAT 5700, Strategic Management
    - Most recent syllabus is [here](files/STRAT_5700_Syllabus_Fall_2015.pdf).

 
___


# **Teaching Awards**
 - [2018 Teaching Excellence Award](https://www.utep.edu/business/undergraduate/Faculty-Teaching-Awards.html) (Management) from the UTEP College of Business Administration